import { HuntSalesBar } from './HuntSalesBar';

export default function Home() {
  return <>
    <HuntSalesBar endsAt={process.env.HUNT_SALES_END_AT} />
    <header className="site-header"><div className="container header-inner"><a className="brand" href="/" aria-label="ShowHunt home"><img className="brand-logo" src="/brand/showhunt-logo-light.svg" alt="" width={960} height={380} /></a><nav aria-label="Main navigation"><a href="#discover">Discover</a><a href="#how-it-works">How it works</a></nav></div></header>
    <main id="main">
      <section className="hero"><div className="container hero-grid"><div><p className="eyebrow">Fresh finds. Everyday possibilities.</p><h1>Your next favourite<br/>starts here.</h1><p className="intro">A simpler way to discover and shop. Thoughtful choices, clear information, and a little more joy in your everyday.</p><a className="button" href="#discover">Meet ShowHunt <span aria-hidden="true">&nbsp; →</span></a></div><aside className="hero-note"><p className="eyebrow">Ghana first. You always.</p><h2>Good things are<br/>on their way.</h2><p>We’re getting ready to bring ShowHunt to Greater Accra. Our store isn’t taking orders yet. Explore what we’re building below.</p></aside></div></section>
      <section id="discover" className="section"><div className="container"><span className="badge">Introducing ShowHunt</span><h2>Shopping that feels simple.</h2><p className="muted">Less friction. More room to find something you love.</p><div className="cards"><article className="card"><span className="number">01 / DISCOVER</span><h3>Find your everyday favourite</h3><p className="muted">Browse a growing selection with clear product details and availability.</p></article><article className="card"><span className="number">02 / CHOOSE</span><h3>Know what you’re paying</h3><p className="muted">See your order total and delivery fee before you confirm your purchase.</p></article><article className="card"><span className="number">03 / ENJOY</span><h3>Stay in the loop</h3><p className="muted">Follow your order from confirmation through delivery.</p></article></div></div></section>
      <section id="how-it-works" className="section soft"><div className="container"><p className="eyebrow">Built around your day</p><h2>A local start. A fresh experience.</h2><div className="cards"><article className="card"><h3>Made for mobile</h3><p className="muted">An easy-to-use store designed for shopping from your phone.</p></article><article className="card"><h3>Familiar ways to pay</h3><p className="muted">Mobile Money at launch, with Pay-on-Delivery for eligible products and areas.</p></article><article className="card"><h3>Greater Accra first</h3><p className="muted">Delivery coverage and fees will be shown when the store opens.</p></article></div></div></section>
    </main><footer><div className="container footer-inner"><a className="brand" href="/" aria-label="ShowHunt home"><img className="brand-logo" src="/brand/showhunt-logo-light.svg" alt="" width={960} height={380} /></a><p>Discover something good. Launching soon in Greater Accra.</p></div></footer>
  </>;
}
